#默认使用配置
spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql


  datasource:
    url: jdbc:mysql://localhost:3306/TESTDB?useSSL=false&amp;serverTimezone=UTC
    username: root
    password: lmx@123456
    driver-class-name: com.mysql.jdbc.Driver

    # 使用druid数据源
    type: org.apache.tomcat.jdbc.pool.DataSource


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  type-aliases-package: com.demo.model
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    # 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
    map-underscore-to-camel-case: true


task:
  corn1: 0/10 * * * * ?
  corn2: 0/5 * * * * ?

